 close all
 clear all
 clc
 
 
 Fig=figure('Name','AmplificatorDeInstrumentatie',...
     'Units','normalized',...
     'Position',[0.1 0.1 0.8 0.8],...
     'Color',[204/255 , 204/255 ,255/255],...
     'NumberTitle','off');
 R=12;
 R2=20;
 A1=10;
 A2=8;
 f1=1000;
 DutyCycle=50;
 tip=2;
 N = 2;
 Valim=15;

 
 Bt1=uicontrol('Style','text',...
     'Units','normalized',...
     'Position',[0.2 0.65 0.5 0.05],...
     'FontSize',20,...
     'foregroundcolor','black',...
     'backgroundcolor',[204/255 , 204/255 ,255/255],...
     'String','Amplificator de intrumentatie');
 set(Bt1, 'FontWeight', 'Bold');
 
 uicontrol('Style','text',...
     'Units','normalized',...
     'Position',[0.3 0.3 0.5 0.05],...
     'FontSize',15,...
     'foregroundcolor','black',...
     'backgroundcolor',[204/255 , 204/255 ,255/255],...
     'String','Crisan Nicoleta Andrada');
 
 uicontrol('Style','text',...
     'Units','normalized',...
     'Position',[0.3 0.25 0.5 0.05],...
     'FontSize',15,...
     'foregroundcolor','black',...
     'backgroundcolor',[204/255 , 204/255 ,255/255],...
     'String','Seria A,grupa2121');
 
 uicontrol('Style','pushbutton',...
     'Units','normalized',...
     'Position',[0.2 0.65 0.5 0.05],...
     'FontSize',20,...
     'foregroundcolor','black',...
     'backgroundcolor',[204/255 , 204/255 ,255/255],...
     'String','Amplificator de intrumentatie',...
     'Callback','close;interfata( DutyCycle,f1,tip,R,R2,A1,A2,N,Fig,Valim)');
 
 
 uicontrol('Style','pushbutton',...
     'Units','normalized',...
     'Position',[0.8 0.1 0.09 0.05],...
     'FontSize',20,...
     'foregroundcolor','black',...
     'backgroundcolor',[204/255 , 204/255 ,255/255],...
     'String','close',...
     'Callback','close');
 
 m=uimenu('Label','Proiect');
uimenu(m,'Label','Pagina_principala','Callback','AmplificatorDeInstrumentatie');
uimenu(m,'Label','Interfata','Callback','interfata');
m12=uimenu(m,'Label','Documentatie','Callback','');
      uimenu(m12,'Label','Amplificator de instrumentatie-prezentareWord','Callback','open(''AmplificatorDeInstrumentatie-Word.pdf'')');
       uimenu(m12,'Label','Amplificator de instrumentatie-PowerPoint','Callback','open(''AmplificatorDeInstrumentatie-PowerPoint.pdf'')');
uimenu(m,'Label','Bibliografie','Callback','open(''Bibliografie.pdf'')');
uimenu(m,'Label','Close','Callback','close','Separator','on','Accelerator','Q');

 
 