function interfata( DutyCycle,f1,tip,R,R2,A1,A2,N,Fig,Valim)

Fig=figure('Name','AmplificatorDeInstrumentatie',...
    'Units','normalized',...
    'Position',[0.1 0.1 0.8 0.8],...
    'Color',[204/255 , 204/255 ,255/255],...
    'NumberTitle','off');

%circuit
w=imread('dreptunghi.png');
image(w);
set(gca,'Position',[0.1 0.06 0.3 0.3])
title('Reprezentarea circuitului')
axis off;

%butoane
Panel_semnal=uipanel('Visible','on',...
    'BackgroundColor','white',...
    'ForegroundColor','black',...
    'Title','Parametrii circuitului',...
    'FontSize',11,...
    'TitlePosition','centertop',...
    'Position',[0.05 0.45 0.24 0.5]);

uicontrol('Style','edit',...
    'Units','normalized',...
    'Position',[0.56 0.82 0.3 0.12],...
    'String', R,...
    'Callback','R=str2num(get(gco,''String''));close;interfata( DutyCycle,f1,tip,R,R2,A1,A2,N,Fig,Valim);',...
    'Parent',Panel_semnal);
uicontrol('Style','text',...
    'Units','normalized',...
    'Position',[0.08 0.78 0.4 0.12],...
    'BackgroundColor','white',...
    'ForegroundColor','red',...
    'String', 'R1=R3=R',...
    'Fontsize', 9,...
    'FontWeight','demi',...
    'HorizontalAlignment','left',...
    'Parent',Panel_semnal);
uicontrol('Style','text',...
    'Units','normalized',...
    'Position',[0.86 0.78 0.4 0.12],...
    'BackgroundColor','white',...
    'ForegroundColor','black',...
    'String', 'kOhm',...
    'Fontsize', 9,...
    'FontWeight','bold',...
    'HorizontalAlignment','left',...
    'Parent',Panel_semnal);


Be1=uicontrol('Style','edit',...
    'Units','normalized',...
    'Position',[0.56 0.65 0.3 0.12],...
    'String', R2,...
    'Callback','R2=str2num(get(gco,''String''));close;interfata( DutyCycle,f1,tip,R,R2,A1,A2,N,Fig,Valim);',...
    'Parent',Panel_semnal);
uicontrol('Style','text',...
    'Units','normalized',...
    'Position',[0.08 0.6 0.4 0.12],...
    'BackgroundColor','white',...
    'ForegroundColor','red',...
    'String', 'R2',...
    'Fontsize', 9,...
    'FontWeight','demi',...
    'HorizontalAlignment','left',...
    'Parent',Panel_semnal);

limitareRe2(R2,Be1)
if (R2>50)
    R2=50;
elseif R2<0.005
    R2=0.005;
end

uicontrol('Style','text',...
    'Units','normalized',...
    'Position',[0.86 0.63 0.4 0.12],...
    'BackgroundColor','white',...
    'ForegroundColor','black',...
    'String', 'kOhm',...
    'Fontsize', 9,...
    'FontWeight','bold',...
    'HorizontalAlignment','left',...
    'Parent',Panel_semnal);


Av=1+(2*R/R2);
uicontrol('Style','edit',...
    'Units','normalized',...
    'Position',[0.56 0.5 0.3 0.12],...
    'String', num2str(Av),...
    'Callback','Av=str2num(get(gco,''String''))',...
    'Parent',Panel_semnal);
uicontrol('Style','text',...
    'Units','normalized',...
    'Position',[0.08 0.5 0.45 0.12],...
    'BackgroundColor','white',...
    'ForegroundColor','red',...
    'String', 'Amplitudinea in tensiune',...
    'Fontsize', 9,...
    'FontWeight','demi',...
    'HorizontalAlignment','left',...
    'Parent',Panel_semnal);


vout=(1+2*(R/R2))*(A1-A2);
uicontrol('Style','edit',...
    'Units','normalized',...
    'Position',[0.56 0.35 0.3 0.12],...
    'String', vout,...
    'Callback','vout=str2num(get(gco,''String'')',...
    'Parent',Panel_semnal);
uicontrol('Style','text',...
    'Units','normalized',...
    'Position',[0.08 0.35 0.45 0.12],...
    'BackgroundColor','white',...
    'ForegroundColor','red',...
    'String', 'Tensiunea de iesire',...
    'Fontsize', 9,...
    'FontWeight','demi',...
    'HorizontalAlignment','left',...
    'Parent',Panel_semnal);
uicontrol('Style','text',...
    'Units','normalized',...
    'Position',[0.86 0.3 0.4 0.12],...
    'BackgroundColor','white',...
    'ForegroundColor','black',...
    'String', 'V',...
    'Fontsize', 9,...
    'FontWeight','bold',...
    'HorizontalAlignment','left',...
    'Parent',Panel_semnal)


I=(A1-A2)/R2;
uicontrol('Style','edit',...
    'Units','normalized',...
    'Position',[0.56 0.20 0.3 0.12],...
    'String', I,...
    'Callback','I=str2num(get(gco,''String'')',...
    'Parent',Panel_semnal);
uicontrol('Style','text',...
    'Units','normalized',...
    'Position',[0.08 0.18 0.45 0.12],...
    'BackgroundColor','white',...
    'ForegroundColor','red',...
    'String', 'Curentul',...
    'Fontsize', 9,...
    'FontWeight','demi',...
    'HorizontalAlignment','left',...
    'Parent',Panel_semnal);
uicontrol('Style','text',...
    'Units','normalized',...
    'Position',[0.86 0.16 0.4 0.12],...
    'BackgroundColor','white',...
    'ForegroundColor','black',...
    'String', 'mA',...
    'Fontsize', 9,...
    'FontWeight','bold',...
    'HorizontalAlignment','left',...
    'Parent',Panel_semnal)




Panel_semnal=uipanel('Visible','on',...
    'BackgroundColor','white',...
    'ForegroundColor','black',...
    'Title','Parametrii semnal',...
    'FontSize',11,...
    'TitlePosition','centertop',...
    'Position',[0.3 0.65 0.2 0.3]);


uicontrol('Style','text',...
    'Units','normalized',...
    'Position',[0.08 0.78 0.4 0.15],...
    'BackgroundColor','white',...
    'ForegroundColor','red',...
    'String', 'f1[Hz]',...
    'Fontsize', 9,...
    'FontWeight','demi',...
    'HorizontalAlignment','left',...
    'Parent',Panel_semnal);
Be2=uicontrol('Style','edit',...
    'Units','normalized',...
    'Position',[0.5 0.82 0.4 0.12],...
    'String', num2str(f1),...
    'Parent',Panel_semnal,...
    'Callback','f1=str2num(get(gco,''String''));close;interfata( DutyCycle,f1,tip,R,R2,A1,A2,N,Fig,Valim)');

limitareVCC(f1,Be2)
if f1>2000
    f1=2000;
elseif f1<200
    f1=200;
end



Bt3=uicontrol('Style','text',...
    'Units','normalized',...
    'Position',[0.08 0.62 0.4 0.15],...
    'BackgroundColor','white',...
    'ForegroundColor','red',...
    'String', 'DutyCycle',...
    'Fontsize', 9,...
    'FontWeight','demi',...
    'HorizontalAlignment','left',...
    'Parent',Panel_semnal);
Be3=uicontrol('Style','edit',...
    'Units','normalized',...
    'Position',[0.5 0.67 0.4 0.12],...
    'String', num2str(DutyCycle),...
    'Parent',Panel_semnal,...
    'Callback','DutyCycle=str2num(get(gco,''String''));close;interfata( DutyCycle,f1,tip,R,R2,A1,A2,N,Fig,Valim)');

limitare_VCC2(DutyCycle,Be3)
if DutyCycle>90
    DutyCycle=90;
elseif DutyCycle<10
    DutyCycle=10;
end

disable_PopUp(tip,Be3)
  if tip == 2
    set(Be3,'Enable','on');
else
    set(Be3,'Enable','off');
  end

uicontrol('Style','edit',...
    'Units','normalized',...
    'Position',[0.5 0.52 0.4 0.12],...
    'String', num2str(A1),...
    'Callback','A1=str2num(get(gco,''String'')),close,interfata(DutyCycle,f1,tip,R,R2,A1,A2,N,Fig,Valim);',...
    'Parent',Panel_semnal);

uicontrol('Style','text',...
    'Units','normalized',...
    'Position',[0.08 0.48 0.4 0.15],...
    'BackgroundColor','white',...
    'ForegroundColor','red',...
    'String', 'A1[V]',...
    'Fontsize', 9,...
    'FontWeight','demi',...
    'HorizontalAlignment','left',...
    'Parent',Panel_semnal);
uicontrol('Style','edit',...
    'Units','normalized',...
    'Position',[0.5 0.35 0.4 0.12],...
    'String', num2str(A2),...
    'Callback','A2=str2num(get(gco,''String''));close;interfata( DutyCycle,f1,tip,R,R2,A1,A2,N,Fig,Valim);',...
    'Parent',Panel_semnal);
uicontrol('Style','text',...
    'Units','normalized',...
    'Position',[0.08 0.33 0.4 0.15],...
    'BackgroundColor','white',...
    'ForegroundColor','red',...
    'String', 'A2[V]',...
    'Fontsize', 9,...
    'FontWeight','demi',...
    'HorizontalAlignment','left',...
    'Parent',Panel_semnal);

Be4=uicontrol('Style','edit',...
    'Units','normalized',...
    'Position',[0.5 0.19 0.4 0.12],...
    'String', num2str(Valim),...
    'Callback','Valim=str2num(get(gco,''String''));close;interfata( DutyCycle,f1,tip,R,R2,A1,A2,N,Fig,Valim);',...
    'Parent',Panel_semnal);
    
uicontrol('Style','text',...
          'Units','normalized',...
          'Position',[0.08 0.15 0.15 0.15],...
          'BackgroundColor','white',...
          'ForegroundColor','red',...
          'Parent',Panel_semnal,...
          'Fontsize', 9,...
          'String','Valim');
      
limitare_VCC3(Valim,Be4)
  if Valim <-15
      Valim=-15;
  elseif Valim > 15
      Valim=15;
  end


uicontrol('Style','PopupMenu',...
    'Units','normalized',...
    'Position',[0.3 0.5 0.1 0.1],...
    'String','Cosinusoidal|Dreptunghiular|Triunghiular|Dinte',....
    'Value',tip,...
    'Callback','tip = get(gco,''Value'');close;interfata( DutyCycle,f1,tip,R,R2,A1,A2,N,Fig,Valim);');
refreshimg(tip)
switch tip
    case 1
        w=imread('cosinus.png');
        image(w);
        set(gca,'Position',[0.1 0.06 0.3 0.3])
        title('Reprezentarea circuitului')
        axis off;
    case 2
        w=imread('dreptunghi.png');
        image(w);
        set(gca,'Position',[0.1 0.06 0.3 0.3])
        title('Reprezentarea circuitului')
        axis off;
    case 3
        w=imread('triunghi.png');
        image(w);
        set(gca,'Position',[0.1 0.06 0.3 0.3])
        title('Reprezentarea circuitului')
        axis off;
    otherwise
        w=imread('dinte.png');
        image(w);
        set(gca,'Position',[0.1 0.06 0.3 0.3])
        title('Reprezentarea circuitului')
        axis off;
end


uicontrol('Style','slider',...
    'Units','normalized',...
    'Position',[0.65 0.03 0.2 0.03],...
    'Min',1,'Max',15,'value',N,...
    'Callback','N=get(gco,''Value'');close;interfata(DutyCycle,f1,tip,R,R2,A1,A2,N,Fig,Valim);');


%reprezentari grafice
f2=1000;
% t1=1/f1;
Tpas=1/max(f1,f2);
Tm=1/min(f1,f2);
t = 0:Tpas/50:N*Tm;

a = A2 * sin(2 * pi * f2  *t);

subplot(322)

plot(t,a,'Color','b','LineWidth',0.5)

title('Semnal sinusoidal');
grid on;

if tip==1
    b = A1 * cos(2 * pi * f2  *t);
elseif tip==2
    b=A1*square(2*pi*f1*t,DutyCycle);
elseif tip==3
    b=A1*sawtooth(2*pi*f1*t,0.5);
else
    b=(2*A1/pi)*atan(tan(2*pi*f1*t/2));
end

subplot(324);
plot(t,b,'Color','m','LineWidth',0.5);
grid on;
refreshtitle(tip);


vout=(1+2*(R/R2))*(b-a);

for i=1:length(t)
if vout(i)>Valim
    vout(i)=Valim;
elseif vout(i)<-Valim
    vout(i)=-Valim;
end
end

subplot(326);
plot(t,vout,'Color','b','LineWidth',0.5);
title('Semnal de iesire');
grid on;


if A1 > 20
    set(Fig,'color','w');
else
    set(Fig,'color','#ccccff');
end

 if Valim <-15
      Valim=-15;
  elseif Valim > 15
      Valim=15;
 end

 Bp=uicontrol('Style','radio',...
               'Units','normalized',...
               'Position',[0.3 0.5 0.16 0.05],...
               'foregroundcolor','k',...
               'FontSize',10,...
               'backgroundcolor',[204/255 , 204/255 ,255/255],...
               'String','CLOSE',...
               'Callback','close');
           
           Bi=uicontrol('Style','pushbutton',...
               'Units','normalized',...
               'Position',[0.01 0.01 0.1 0.05],...
               'String','ÎNAPOI',...
               'Backgroundcolor',[204/255 , 204/255 ,255/255],...
               'Foregroundcolor','k',...
               'Fontsize',10,...
               'Callback','AmplificatorDeInstrumentatie');
 
 m=uimenu('Label','Proiect');
uimenu(m,'Label','Pagina_principala','Callback','AmplificatorDeInstrumentatie');
uimenu(m,'Label','Interfata','Callback','interfata( DutyCycle,f1,tip,R,R2,A1,A2,N,Fig,Valim)');
m12=uimenu(m,'Label','Documentatie','Callback','');
      uimenu(m12,'Label','Amplificator de instrumentatie-prezentareWord','Callback','open(''AmplificatorDeInstrumentatie-Word.pdf'')');
       uimenu(m12,'Label','Amplificator de instrumentatie-PowerPoint','Callback','open(''AmplificatorDeInstrumentatie-PowerPoint.pdf'')');
uimenu(m,'Label','Bibliografie','Callback','open(''Bibliografie.pdf'')');
uimenu(m,'Label','Close','Callback','close','Separator','on','Accelerator','Q');

end
